import { useEffect, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { AdminHeader, Alert } from "../components/AdminLayout";
import { GaugeChart } from "../components/charts/GaugeChart";
import { BarChart } from "../components/charts/BarChart";
import { api, mediaUrl, money } from "../services/api";
import { useAuth } from "../context/AuthContext";

const useLoad = (url, params) => { const [data, setData] = useState(null); const [error, setError] = useState(""); const paramsKey = JSON.stringify(params || {}); const load = () => api.get(url, { params: JSON.parse(paramsKey) }).then((r) => setData(r.data)).catch((e) => setError(e.response?.data?.detail || "Erro ao carregar.")); useEffect(() => { load(); }, [url, paramsKey]); return { data, error, load }; }; // eslint-disable-line react-hooks/exhaustive-deps
const useList = (url, params) => { const result = useLoad(url, params); return { ...result, data: Array.isArray(result.data) ? result.data : [] }; };
const FormField = ({ label, name, type = "text", defaultValue = "", required = false, children, ...rest }) => <div className="form-group"><label>{label}</label>{children || <input className="form-control" name={name} type={type} defaultValue={defaultValue ?? ""} required={required} {...rest} />}</div>;
const Table = ({ headers, rows, render }) => <div className="table-wrap"><table className="dash-table"><thead><tr>{headers.map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(render)}</tbody></table></div>;
const Empty = ({ text }) => <div className="empty-state"><i className="fas fa-box-open" /><p>{text}</p></div>;
const Badge = ({ children, tone = "gray" }) => <span className={`badge badge-${tone}`}>{children}</span>;
const Notice = ({ notice }) => notice?.message ? <Alert>{notice.message}</Alert> : notice?.error ? <Alert type="error">{notice.error}</Alert> : null;
// Ação compacta: apenas o ícone, com o texto no tooltip e para leitores de tela.
const IconBtn = ({ as: Tag = "button", icon, label, tone = "outline", ...rest }) => <Tag className={`btn btn-sm btn-${tone} btn-icon`} title={label} aria-label={label} {...(Tag === "button" ? { type: "button" } : {})} {...rest}><i className={`fas ${icon}`} aria-hidden="true" /></Tag>;
const StatusBadge = ({ status }) => { const [tone, icon, label] = status === "active" ? ["is-active", "fa-circle-check", "Ativo"] : status === "pending" ? ["is-pending", "fa-clock", "Pendente"] : ["is-off", "fa-circle-minus", "Inativo"]; return <span className={`badge-soft ${tone}`} title={status}><i className={`fas ${icon}`} aria-hidden="true" />{label}</span>; };
const Switch = ({ checked, onChange, label }) => <label className="pm-switch" title={label}><input type="checkbox" checked={Boolean(checked)} onChange={onChange} aria-label={label} /><span className="pm-switch-track" aria-hidden="true" /><span className="pm-switch-label">Modelo</span></label>;

export function AgentDashboardPage() {
  const { data } = useLoad("/agent/dashboard"); const { user } = useAuth();
  return <><AdminHeader title="Dashboard" />{!data ? <Empty text="Carregando..." /> : <><div className="metrics"><div className="metric"><h2>{data.total_clients}</h2><p>Restaurantes cadastrados</p></div><div className="metric"><h2>{data.active_clients}</h2><p>Clientes ativos</p></div><div className="metric"><h2>{money(data.available_balance)}</h2><p>Saldo disponível</p></div><div className="metric"><h2>{money(data.commissions_total)}</h2><p>Comissões acumuladas</p></div></div><div className="grid-2"><div className="card"><div className="card-header"><h3>Atalhos</h3></div><div className="card-body action-row">{user.role === "gerente" && <Link className="btn btn-primary" to="/gerente/representantes">Representantes</Link>}<Link className="btn btn-outline" to={`/${user.role}/restaurantes`}>Restaurantes</Link><Link className="btn btn-outline" to={`/${user.role}/mapa`}>Mapa</Link></div></div><div className="card"><div className="card-header"><h3>Comissões</h3></div><div className="card-body"><p>Consulte o extrato e solicite saques pelo painel.</p></div></div></div></>}
  </>;
}

export function AgentRestaurantsPage() {
  const { data, load } = useList("/agent/restaurants"); const { user } = useAuth(); const [notice, setNotice] = useState({}); const [edit, setEdit] = useState(null);
  const submit = async (e) => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); if (edit) body.id = edit.id; try { await api.post("/agent/restaurants", body); setNotice({ message: edit ? "Restaurante atualizado." : "Restaurante cadastrado." }); setEdit(null); e.currentTarget.reset(); load(); } catch (err) { setNotice({ error: err.response?.data?.detail }); } };
  const remove = async (id) => { if (!window.confirm("Remover este lead?")) return; try { await api.delete(`/agent/restaurants/${id}`); load(); } catch (err) { setNotice({ error: err.response?.data?.detail }); } };
  return <><AdminHeader title={user.role === "representante" ? "Meus Restaurantes" : "Restaurantes"} /><Notice notice={notice} /><div className="card" style={{ marginBottom: 27 }}><div className="card-header"><h3>{edit ? "Editar Restaurante" : "Cadastrar Restaurante"}</h3></div><div className="card-body"><p style={{ color: "var(--muted)", fontSize: 12 }}>Endereço é opcional, mas necessário para o mapa.</p><form onSubmit={submit} key={edit?.id || "new"}><div className="grid-3"><FormField label="Nome" name="name" defaultValue={edit?.name} required /><FormField label="E-mail" name="email" type="email" defaultValue={edit?.email} required />{!edit && <FormField label="Senha" name="password" type="password" required />}<FormField label="Endereço" name="address" defaultValue={edit?.address} /><FormField label="Latitude" name="latitude" defaultValue={edit?.latitude} /><FormField label="Longitude" name="longitude" defaultValue={edit?.longitude} /></div><div className="action-row"><button className="btn btn-primary">{edit ? "Salvar" : "Cadastrar"}</button>{edit && <button type="button" className="btn btn-outline" onClick={() => setEdit(null)}>Cancelar</button>}</div></form></div></div><div className="card"><div className="card-header"><h3>Restaurantes</h3><Badge tone="blue">{data.length}</Badge></div><div className="card-body">{!data.length ? <Empty text="Nenhum restaurante cadastrado." /> : <Table headers={["Nome", "Responsável", "E-mail", "Endereço", "Status", "Ações"]} rows={data} render={(r) => <tr key={r.id}><td><strong>{r.name}</strong></td><td>{r.agent_name}</td><td>{r.email}</td><td>{r.address || "—"}</td><td><Badge tone={r.status === "active" ? "green" : r.status === "pending" ? "orange" : "red"}>{r.status}</Badge></td><td><div className="action-row"><button className="btn btn-sm btn-outline" onClick={() => setEdit(r)}><i className="fas fa-pen" /></button>{user.role === "representante" && <button className="btn btn-sm btn-danger" onClick={() => remove(r.id)}><i className="fas fa-trash" /></button>}</div></td></tr>} />}</div></div></>;
}

export function RepresentativesPage() {
  const { data, load } = useList("/agent/representatives"); const [notice, setNotice] = useState({});
  const submit = async (e) => { e.preventDefault(); try { await api.post("/agent/representatives", Object.fromEntries(new FormData(e.currentTarget))); setNotice({ message: "Representante cadastrado." }); e.currentTarget.reset(); load(); } catch (err) { setNotice({ error: err.response?.data?.detail }); } };
  const update = async (e, id) => { e.preventDefault(); await api.post("/agent/representatives", { id, ...Object.fromEntries(new FormData(e.currentTarget)) }); load(); };
  return <><AdminHeader title="Representantes" /><Notice notice={notice} /><div className="card" style={{ marginBottom: 27 }}><div className="card-header"><h3>Cadastrar Representante</h3></div><div className="card-body"><form onSubmit={submit}><div className="grid-3"><FormField label="Nome" name="name" required /><FormField label="E-mail" name="email" type="email" required /><FormField label="Senha" name="password" type="password" required /><FormField label="% Adesão" name="pct_adesao" type="number" step="0.01" /><FormField label="% Mensalidade" name="pct_mensalidade" type="number" step="0.01" /></div><button className="btn btn-primary">Cadastrar</button></form></div></div><div className="card"><div className="card-header"><h3>Representantes</h3><Badge tone="blue">{data.length}</Badge></div><div className="card-body"><Table headers={["Nome", "E-mail", "% Adesão", "% Mensal", "Status", "Atualizar"]} rows={data} render={(r) => <tr key={r.id}><td>{r.name}</td><td>{r.email}</td><td>{r.pct_adesao ?? "—"}</td><td>{r.pct_mensalidade ?? "—"}</td><td><Badge tone={r.is_active ? "green" : "red"}>{r.is_active ? "Ativo" : "Inativo"}</Badge></td><td><form className="action-row" onSubmit={(e) => update(e, r.id)}><input className="form-control" style={{ width: 80 }} name="pct_adesao" defaultValue={r.pct_adesao} /><input className="form-control" style={{ width: 80 }} name="pct_mensalidade" defaultValue={r.pct_mensalidade} /><button className="btn btn-sm btn-primary">Salvar</button></form></td></tr>} /></div></div></>;
}

export function CommissionsPage() {
  const { data } = useList("/agent/commissions"); return <><AdminHeader title="Comissões" /><div className="card"><div className="card-header"><h3>Extrato de Comissões</h3><Badge tone="blue">{data.length}</Badge></div><div className="card-body">{!data.length ? <Empty text="Nenhuma comissão registrada." /> : <Table headers={["Data", "Tipo", "Base", "%", "Valor", "Disponível em", "Status"]} rows={data} render={(c) => <tr key={c.id}><td>{c.created_at}</td><td>{c.kind}</td><td>{money(c.base_cents)}</td><td>{c.pct}%</td><td><strong>{money(c.amount_cents)}</strong></td><td>{c.available_at}</td><td><Badge tone={c.status === "available" ? "green" : "gray"}>{c.status}</Badge></td></tr>} />}</div></div></>;
}

export function WithdrawPage() {
  const { data, load } = useLoad("/agent/withdrawals"); const { user, refresh } = useAuth(); const [notice, setNotice] = useState({}); const submit = async (e) => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); body.amount_cents = Math.round(Number(String(body.amount).replace(".", "").replace(",", ".")) * 100); try { await api.post("/agent/withdrawals", body); setNotice({ message: "Saque solicitado." }); load(); } catch (err) { setNotice({ error: err.response?.data?.detail }); } };
  return <><AdminHeader title="Saque" /><Notice notice={notice} />{!data ? <Empty text="Carregando..." /> : <><div className="metrics"><div className="metric"><h2>{money(data.balance)}</h2><p>Saldo disponível</p></div><div className="metric"><h2>{money(data.minimum)}</h2><p>Saque mínimo</p></div><div className="metric"><h2>{user.email_verified_at ? "OK" : "Pendente"}</h2><p>E-mail</p></div><div className="metric"><h2>{user.pix_verified_at ? "OK" : "Pendente"}</h2><p>PIX</p></div></div>{(!user.email_verified_at || !user.pix_verified_at) && <div className="card" style={{ marginBottom: 27 }}><div className="card-header"><h3>Validações para receber</h3></div><div className="card-body">{!user.email_verified_at && <button className="btn btn-primary" onClick={() => api.post("/auth/verification/send").then(() => setNotice({ message: "E-mail de validação enviado." })).catch((e) => setNotice({ error: e.response?.data?.detail }))}>Enviar validação de e-mail</button>}{!user.pix_verified_at && <form onSubmit={(e) => { e.preventDefault(); api.post("/agent/pix/validate", Object.fromEntries(new FormData(e.currentTarget))).then(() => { refresh(); setNotice({ message: "Chave PIX validada." }); }); }}><FormField label="Chave PIX" name="pix_key" defaultValue={user.pix_key} required /><button className="btn btn-primary">Salvar e validar PIX</button></form>}</div></div>}<div className="card" style={{ marginBottom: 27 }}><div className="card-header"><h3>Solicitar Saque</h3></div><div className="card-body"><form onSubmit={submit}><div className="grid-2"><FormField label="Valor (R$)" name="amount" required /><FormField label="Chave PIX" name="pix_key" defaultValue={user.pix_key} required /></div><button className="btn btn-primary" disabled={!user.email_verified_at || !user.pix_verified_at}>Solicitar</button></form></div></div><div className="card"><div className="card-header"><h3>Histórico</h3></div><div className="card-body"><Table headers={["Data", "Valor", "PIX", "Status", "Observação"]} rows={data.rows} render={(w) => <tr key={w.id}><td>{w.requested_at}</td><td>{money(w.amount_cents)}</td><td>{w.pix_key}</td><td><Badge tone={w.status === "approved" ? "green" : w.status === "pending" ? "orange" : "red"}>{w.status}</Badge></td><td>{w.note || "—"}</td></tr>} /></div></div></>}</>;
}

export function PlatformSettingsPage() {
  const { data, load } = useLoad("/superadmin/platform-settings"); const [notice, setNotice] = useState({}); if (!data) return <Empty text="Carregando..." />; const submit = async (e) => { e.preventDefault(); try { await api.post("/superadmin/platform-settings", Object.fromEntries(new FormData(e.currentTarget))); setNotice({ message: "Valores atualizados com sucesso." }); load(); } catch (err) { setNotice({ error: err.response?.data?.detail }); } };
  return <><AdminHeader title="Plano & Valores" /><Notice notice={notice} /><div className="card"><div className="card-header"><h3>Configurações do Plano</h3></div><div className="card-body"><form onSubmit={submit}><div className="grid-2">{[["mensalidade_cents", "Mensalidade (centavos)"], ["video_price_cents", "Valor por Vídeo (centavos)"], ["min_withdrawal_cents", "Saque Mínimo (centavos)"], ["override_pct_adesao", "Override Gerente - Venda (%)"], ["override_pct_mensalidade", "Override Gerente - Mensalidade (%)"]].map(([name, label]) => <FormField key={name} label={label} name={name} type="number" step={name.startsWith("override") ? "0.01" : undefined} defaultValue={data[name]} />)}</div><button className="btn btn-primary">Salvar</button></form></div></div></>;
}

export function MaterialsPage() {
  const { data } = useList("/agent/materials"); return <><AdminHeader title="Material de Apoio" />{!data.length ? <Empty text="Nenhum material disponível." /> : <div className="material-grid">{data.map((m) => <article className="material-card" key={m.id}><Badge>{m.material_type}</Badge><h3>{m.title}</h3><p>{m.description}</p><a className="btn btn-outline" href={mediaUrl(m.material_type === "video_link" ? m.external_url : m.file_path)} target="_blank" rel="noreferrer">Abrir material</a></article>)}</div>}</>;
}

export function MapPage() {
  const { data, load } = useLoad("/agent/routes"); const [selected, setSelected] = useState([]); const [notice, setNotice] = useState({}); if (!data) return <><AdminHeader title="Mapa" /><Empty text="Carregando..." /></>;
  const save = async () => { const stops = data.restaurants.filter((r) => selected.includes(r.id)).map((r) => ({ name: r.name, address: r.address, lat: r.latitude, lng: r.longitude })); try { await api.post("/agent/routes", { title: `Rota ${new Date().toLocaleString("pt-BR")}`, stops }); setNotice({ message: "Rota salva com sucesso." }); setSelected([]); load(); } catch (err) { setNotice({ error: err.response?.data?.detail }); } };
  const mapsUrl = (route) => { const points = (route.stops || []).filter((s) => s.lat && s.lng); if (!points.length) return "https://www.google.com/maps"; const destination = points.at(-1); const waypoints = points.slice(0, -1).map((s) => `${s.lat},${s.lng}`).join("|"); return `https://www.google.com/maps/dir/?api=1&travelmode=driving&destination=${destination.lat},${destination.lng}${waypoints ? `&waypoints=${encodeURIComponent(waypoints)}` : ""}`; };
  return <><AdminHeader title="Mapa" /><Notice notice={notice} /><div className="grid-2"><div className="card"><div className="card-header"><h3>Restaurantes vinculados</h3></div><div className="card-body">{data.restaurants.map((r) => <label key={r.id} style={{ display: "flex", gap: 10, padding: 10 }}><input type="checkbox" checked={selected.includes(r.id)} onChange={() => setSelected(selected.includes(r.id) ? selected.filter((id) => id !== r.id) : [...selected, r.id])} /><span><strong>{r.name}</strong><br /><small>{r.address || "Sem endereço"}</small></span></label>)}<button className="btn btn-primary" disabled={!selected.length} onClick={save}>Salvar rota</button></div></div><div className="route-map-placeholder"><div><i className="fas fa-map-location-dot" /> Selecione estabelecimentos para montar a rota.</div></div></div><div className="card" style={{ marginTop: 27 }}><div className="card-header"><h3>Rotas salvas</h3></div><div className="card-body"><Table headers={["Título", "Paradas", "Status", "Google Maps", "Ações"]} rows={data.routes} render={(r) => <tr key={r.id}><td>{r.title}</td><td>{r.stops?.length || 0}</td><td><Badge tone={r.status === "completed" ? "green" : "orange"}>{r.status}</Badge></td><td><a className="btn btn-sm btn-outline" href={mapsUrl(r)} target="_blank" rel="noreferrer">Abrir</a></td><td><div className="action-row"><button className="btn btn-sm btn-success" onClick={() => api.patch(`/agent/routes/${r.id}`, { action: "complete", rating: 5 }).then(load)}>Concluir</button><button className="btn btn-sm btn-danger" onClick={() => api.patch(`/agent/routes/${r.id}`, { action: "delete" }).then(load)}>Excluir</button></div></td></tr>} /></div></div></>;
}

export function SuperDashboardPage() {
  const { data } = useLoad("/superadmin/dashboard");
  if (!data) return <><AdminHeader title="Dashboard" /><Empty text="Carregando..." /></>;
  const months = data.signups_by_month || [];
  const lastMonth = months[months.length - 1]?.value || 0;
  const prevMonth = months[months.length - 2]?.value || 0;
  const trend = prevMonth ? Math.round(((lastMonth - prevMonth) / prevMonth) * 100) : lastMonth > 0 ? 100 : 0;
  const activePct = data.restaurants ? Math.round((data.active_restaurants / data.restaurants) * 100) : 0;
  const segments = [
    { label: "Ativos", value: data.active_restaurants },
    { label: "Pendentes", value: data.pending_restaurants },
    { label: "Suspensos", value: data.suspended_restaurants },
  ];
  const segTotal = Math.max(1, data.restaurants);
  return <>
    <AdminHeader title="Dashboard" />
    <div className="metrics">
      <div className="metric revenue">
        <div className="metric-title">Restaurantes cadastrados</div>
        <div className="metric-value">{data.restaurants}</div>
        <div className="metric-foot"><span className="metric-trend">{trend >= 0 ? "▲" : "▼"} {Math.abs(trend)}%</span><span>vs. mês anterior</span></div>
      </div>
      <div className="metric">
        <div className="metric-title">Agentes</div>
        <div className="metric-value">{data.agents}</div>
        <div className="metric-foot"><span>{data.pending_requests} solicitação(ões) de vídeo pendente(s)</span></div>
      </div>
      <div className="metric">
        <div className="metric-title">Restaurantes por status</div>
        <div className="metric-value">{data.restaurants}</div>
        <div className="target-track">{segments.map((seg) => <span key={seg.label} className="target-seg" style={{ flex: Math.max(0.06, seg.value / segTotal) }} title={`${seg.label}: ${seg.value}`} />)}</div>
        <div className="metric-legend">{segments.map((seg) => <span key={seg.label}><i className="dot" />{seg.label} ({seg.value})</span>)}</div>
      </div>
    </div>
    <div className="dash-lower">
      <div className="gauge-card">
        <h3>Restaurantes ativos</h3>
        <div className="subtle">Proporção sobre o total cadastrado</div>
        <GaugeChart value={activePct} label={`${activePct}%`} sublabel={`${data.active_restaurants} de ${data.restaurants}`} />
      </div>
      <div className="chart-card">
        <h3>Novos cadastros</h3>
        <div className="subtle">Restaurantes cadastrados nos últimos 6 meses</div>
        <BarChart data={months} formatValue={(v) => `${v} restaurante(s)`} />
      </div>
    </div>
    <div className="card" style={{ marginTop: "var(--gap)" }}>
      <div className="card-header"><h3>Financeiro & operação</h3></div>
      <div className="card-body grid-2">
        <div><strong style={{ fontSize: 20 }}>{data.pending_requests}</strong><p style={{ margin: "4px 0 0", color: "var(--muted)", fontSize: 12 }}>Solicitações de vídeo pendentes</p></div>
        <div><strong style={{ fontSize: 20 }}>{data.pending_withdrawals}</strong><p style={{ margin: "4px 0 0", color: "var(--muted)", fontSize: 12 }}>Saques de agentes pendentes</p></div>
      </div>
    </div>
  </>;
}

export function SuperRestaurantsPage() {
  const { data, load } = useList("/superadmin/restaurants"); const [notice, setNotice] = useState({}); const send = async (body) => { try { await api.post("/superadmin/restaurants", body); setNotice({ message: body.action === "delete" ? "Restaurante excluído." : "Restaurante atualizado." }); load(); } catch (err) { setNotice({ error: err.response?.data?.detail }); } }; const submit = (e) => { e.preventDefault(); send(Object.fromEntries(new FormData(e.currentTarget))); e.currentTarget.reset(); };
  const remove = (r) => { if (window.confirm(`Excluir "${r.name}" definitivamente?\n\nSerão apagados o cadastro, o cardápio, as mídias, as avaliações, as páginas de bio e as métricas deste restaurante. Comissões e pagamentos são mantidos para auditoria.\n\nEsta ação não pode ser desfeita.`)) send({ action: "delete", id: r.id }); };
  return <><AdminHeader title="Restaurantes" /><Notice notice={notice} /><div className="card" style={{ marginBottom: 27 }}><div className="card-header"><h3>Cadastrar Restaurante</h3></div><div className="card-body"><form onSubmit={submit}><div className="grid-3"><FormField label="Nome" name="name" required /><FormField label="E-mail" name="email" type="email" required /><FormField label="Senha" name="password" required /></div><button className="btn btn-primary">Cadastrar</button></form></div></div><div className="card"><div className="card-header"><h3>Todos os Restaurantes</h3><Badge tone="blue">{data.length}</Badge></div><div className="card-body"><Table headers={["Nome", "E-mail", "Status", "Vendedor", "Modelo", "Ações"]} rows={data} render={(r) => <tr key={r.id}><td><strong>{r.name}</strong><br /><small>/{r.slug}</small></td><td>{r.email}</td><td><StatusBadge status={r.status} /></td><td>{r.seller_name}</td><td><Switch checked={r.is_model} onChange={() => send({ action: "toggle_model", id: r.id })} label={`${r.is_model ? "Desativar" : "Ativar"} restaurante modelo — ${r.name}`} /></td><td><div className="action-row"><IconBtn as={Link} to={`/superadmin/restaurante?id=${r.id}`} tone="primary" icon="fa-eye" label={`Ver detalhes de ${r.name}`} /><IconBtn tone="outline" icon={r.status === "active" ? "fa-ban" : "fa-play"} label={r.status === "active" ? `Suspender ${r.name}` : `Reativar ${r.name}`} onClick={() => send({ action: "toggle", id: r.id })} /><IconBtn tone="danger" icon="fa-trash" label={`Excluir ${r.name}`} data-testid={`delete-restaurant-${r.id}`} onClick={() => remove(r)} /></div></td></tr>} /></div></div></>;
}

export function SuperAgentsPage() {
  const { data, load } = useList("/superadmin/agents"); const [notice, setNotice] = useState({}); const send = async (body) => { try { await api.post("/superadmin/agents", body); setNotice({ message: "Agente atualizado." }); load(); } catch (err) { setNotice({ error: err.response?.data?.detail }); } }; const managers = data.filter((a) => a.role === "gerente");
  return <><AdminHeader title="Agentes" /><Notice notice={notice} /><div className="card" style={{ marginBottom: 27 }}><div className="card-header"><h3>Gerentes & Representantes</h3></div><div className="card-body"><Table headers={["Nome", "E-mail", "Papel", "Gerente", "% Adesão", "% Mensal", "Status", "Ações"]} rows={data} render={(a) => <tr key={a.id}><td>{a.name}</td><td>{a.email}</td><td><Badge tone={a.role === "gerente" ? "blue" : "orange"}>{a.role}</Badge></td><td>{a.parent_name}</td><td>{a.pct_adesao ?? "—"}</td><td>{a.pct_mensalidade ?? "—"}</td><td><Badge tone={a.is_active ? "green" : "red"}>{a.is_active ? "Ativo" : "Inativo"}</Badge></td><td><div className="action-row"><button className="btn btn-sm btn-outline" onClick={() => send({ action: "toggle", id: a.id })}>{a.is_active ? "Desativar" : "Ativar"}</button>{a.role === "representante" && <button className="btn btn-sm btn-primary" onClick={() => send({ action: "promote", id: a.id })}>Virar gerente</button>}<button className="btn btn-sm btn-danger" onClick={() => window.confirm("Excluir agente?") && send({ action: "delete", id: a.id })}><i className="fas fa-trash" /></button></div></td></tr>} /></div></div><div className="card"><div className="card-header"><h3>Cadastrar Novo Agente</h3></div><div className="card-body"><form onSubmit={(e) => { e.preventDefault(); send({ action: "add", ...Object.fromEntries(new FormData(e.currentTarget)) }); e.currentTarget.reset(); }}><div className="grid-3"><FormField label="Nome" name="name" required /><FormField label="E-mail" name="email" type="email" required /><FormField label="Senha" name="password" type="password" required /><FormField label="Papel"><select className="form-control" name="role"><option value="gerente">Gerente</option><option value="representante">Representante</option></select></FormField><FormField label="Gerente"><select className="form-control" name="parent_id"><option value="">Nenhum</option>{managers.map((m) => <option value={m.id} key={m.id}>{m.name}</option>)}</select></FormField><FormField label="% Adesão" name="pct_adesao" type="number" step="0.01" /><FormField label="% Mensal" name="pct_mensalidade" type="number" step="0.01" /><FormField label="Máx. representante" name="max_pct_rep" type="number" step="0.01" /></div><button className="btn btn-primary">Cadastrar</button></form></div></div></>;
}

export function PlansPage() {
  const { data, load } = useList("/superadmin/plans"); const [edit, setEdit] = useState(null); const [notice, setNotice] = useState({}); const send = async (body) => { try { await api.post("/superadmin/plans", body); setEdit(null); setNotice({ message: "Plano atualizado." }); load(); } catch (err) { setNotice({ error: err.response?.data?.detail }); } };
  const submit = (e) => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); for (const key of ["price_cents", "discount_value_cents", "periodicity_days"]) body[key] = Number(body[key] || 0); body.discount_percent = Number(body.discount_percent || 0); body.is_active = body.is_active ? 1 : 0; if (edit) body.id = edit.id; send(body); };
  return <><AdminHeader title="Planos" /><Notice notice={notice} /><div className="card" style={{ marginBottom: 27 }}><div className="card-header"><h3>Planos Disponíveis</h3><Badge tone="blue">{data.length}</Badge></div><div className="card-body"><Table headers={["Nome", "Valor", "Desconto", "Periodicidade", "Status", "Ações"]} rows={data} render={(p) => <tr key={p.id}><td><strong>{p.name}</strong><br /><small>{p.description}</small></td><td>{money(p.price_cents)}</td><td>{p.discount_type === "percent" ? `${p.discount_percent}%` : p.discount_type === "fixed" ? money(p.discount_value_cents) : "Sem desconto"}</td><td>{p.periodicity_days} dias</td><td><Badge tone={p.is_active ? "green" : "red"}>{p.is_active ? "Ativo" : "Inativo"}</Badge></td><td><div className="action-row"><button className="btn btn-sm btn-outline" onClick={() => setEdit(p)}>Editar</button><button className="btn btn-sm btn-danger" onClick={() => window.confirm("Excluir plano?") && send({ action: "delete", id: p.id })}>Excluir</button></div></td></tr>} /></div></div><div className="card"><div className="card-header"><h3>{edit ? "Editar Plano" : "Novo Plano"}</h3></div><div className="card-body"><form key={edit?.id || "new"} onSubmit={submit}><div className="grid-3"><FormField label="Nome" name="name" defaultValue={edit?.name} required /><FormField label="Valor base em centavos" name="price_cents" type="number" defaultValue={edit?.price_cents} required /><FormField label="Periodicidade"><select className="form-control" name="periodicity_days" defaultValue={edit?.periodicity_days || 30}><option value="30">Mensal</option><option value="180">Semestral</option><option value="365">Anual</option></select></FormField><FormField label="Tipo de desconto"><select className="form-control" name="discount_type" defaultValue={edit?.discount_type || "none"}><option value="none">Sem desconto</option><option value="percent">Porcentagem</option><option value="fixed">Valor fixo</option></select></FormField><FormField label="Desconto %" name="discount_percent" type="number" step="0.01" defaultValue={edit?.discount_percent} /><FormField label="Desconto em centavos" name="discount_value_cents" type="number" defaultValue={edit?.discount_value_cents} /></div><FormField label="Descrição"><textarea className="form-control" name="description" defaultValue={edit?.description} /></FormField><label><input type="checkbox" name="is_active" defaultChecked={edit ? Boolean(edit.is_active) : true} /> Plano ativo</label><div className="action-row"><button className="btn btn-primary">Salvar</button>{edit && <button className="btn btn-outline" type="button" onClick={() => setEdit(null)}>Cancelar</button>}</div></form></div></div></>;
}

export function CommissionRulesPage() {
  const { data, load } = useList("/superadmin/commission-rules"); const send = (body) => api.post("/superadmin/commission-rules", body).then(load);
  return <><AdminHeader title="Regras de Comissão" /><div className="card" style={{ marginBottom: 27 }}><div className="card-header"><h3>Faixas de Comissão Escalonada</h3></div><div className="card-body"><Table headers={["Mín. Clientes", "% Adesão", "% Mensalidade", "Ação"]} rows={data} render={(r) => <tr key={r.id}><td>{r.min_active_clients}</td><td>{r.pct_adesao}%</td><td>{r.pct_mensalidade}%</td><td>{r.min_active_clients > 0 ? <button className="btn btn-sm btn-danger" onClick={() => send({ action: "delete", id: r.id })}>Excluir</button> : <Badge>Base</Badge>}</td></tr>} /></div></div><div className="card"><div className="card-header"><h3>Adicionar Nova Faixa</h3></div><div className="card-body"><form onSubmit={(e) => { e.preventDefault(); send(Object.fromEntries(new FormData(e.currentTarget))); e.currentTarget.reset(); }}><div className="grid-3"><FormField label="Mín. Clientes Ativos" name="min_active_clients" type="number" required /><FormField label="% Comissão Adesão" name="pct_adesao" type="number" step="0.01" required /><FormField label="% Comissão Mensalidade" name="pct_mensalidade" type="number" step="0.01" required /></div><button className="btn btn-primary">Adicionar Faixa</button></form></div></div></>;
}

export function SuperWithdrawalsPage() {
  const { data, load } = useList("/superadmin/withdrawals"); const decide = (id, action) => api.post("/superadmin/withdrawals", { id, action }).then(load);
  return <><AdminHeader title="Saques" /><div className="card"><div className="card-header"><h3>Solicitações de Saque</h3></div><div className="card-body">{!data.length ? <Empty text="Nenhuma solicitação de saque." /> : <Table headers={["Agente", "Papel", "Valor", "PIX", "Status", "Data", "Ações"]} rows={data} render={(w) => <tr key={w.id}><td>{w.agent?.name}</td><td>{w.agent?.role}</td><td>{money(w.amount_cents)}</td><td>{w.pix_key}</td><td><Badge tone={w.status === "approved" ? "green" : w.status === "pending" ? "orange" : "red"}>{w.status}</Badge></td><td>{w.requested_at}</td><td>{w.status === "pending" && <div className="action-row"><button className="btn btn-sm btn-success" onClick={() => decide(w.id, "approve")}>Aprovar</button><button className="btn btn-sm btn-danger" onClick={() => decide(w.id, "reject")}>Rejeitar</button></div>}</td></tr>} />}</div></div></>;
}

export function SuperMaterialsPage() {
  const { data, load } = useList("/superadmin/materials"); const [notice, setNotice] = useState({}); const submit = async (e) => { e.preventDefault(); try { await api.post("/superadmin/materials", new FormData(e.currentTarget)); setNotice({ message: "Material cadastrado." }); e.currentTarget.reset(); load(); } catch (err) { setNotice({ error: err.response?.data?.detail }); } };
  return <><AdminHeader title="Material de Apoio" /><Notice notice={notice} /><div className="card" style={{ marginBottom: 27 }}><div className="card-header"><h3>Novo Material</h3></div><div className="card-body"><form onSubmit={submit} encType="multipart/form-data"><div className="grid-2"><FormField label="Título" name="title" required /><FormField label="Público"><select className="form-control" name="audience"><option value="all">Todos</option><option value="gerente">Gerentes</option><option value="representante">Representantes</option></select></FormField><FormField label="Tipo"><select className="form-control" name="material_type"><option value="document">Documento</option><option value="file">Arquivo</option><option value="image">Imagem</option><option value="video_file">Vídeo arquivo</option><option value="video_link">Vídeo por link</option></select></FormField><FormField label="Arquivo" name="material_file" type="file" /><FormField label="Link do vídeo" name="external_url" type="url" /></div><FormField label="Descrição"><textarea className="form-control" name="description" /></FormField><label><input type="checkbox" name="is_active" defaultChecked /> Ativo</label><button className="btn btn-primary">Cadastrar Material</button></form></div></div><div className="card"><div className="card-header"><h3>Materiais Cadastrados</h3><Badge tone="blue">{data.length}</Badge></div><div className="card-body"><Table headers={["Material", "Tipo", "Público", "Status", "Ações"]} rows={data} render={(m) => <tr key={m.id}><td><strong>{m.title}</strong><br /><small>{m.description}</small></td><td>{m.material_type}</td><td>{m.audience}</td><td><Badge tone={m.is_active ? "green" : "red"}>{m.is_active ? "Ativo" : "Inativo"}</Badge></td><td><div className="action-row"><a className="btn btn-sm btn-outline" href={mediaUrl(m.external_url || m.file_path)} target="_blank" rel="noreferrer">Abrir</a><button className="btn btn-sm btn-outline" onClick={() => api.patch(`/superadmin/materials/${m.id}/toggle`).then(load)}>Status</button><button className="btn btn-sm btn-danger" onClick={() => api.patch(`/superadmin/materials/${m.id}/delete`).then(load)}>Excluir</button></div></td></tr>} /></div></div></>;
}

export function SuperSettingsPage() {
  const { data, load } = useLoad("/superadmin/settings"); const [notice, setNotice] = useState({}); if (!data) return <Empty text="Carregando..." />; const submit = async (e) => { e.preventDefault(); try { await api.post("/superadmin/settings", Object.fromEntries(new FormData(e.currentTarget))); setNotice({ message: "Configurações de SMTP salvas." }); load(); } catch (err) { setNotice({ error: err.response?.data?.detail }); } };
  return <><AdminHeader title="Configurações" /><Notice notice={notice} /><div className="card"><div className="card-header"><h3>SMTP Global</h3></div><div className="card-body"><form onSubmit={submit}><div className="grid-2"><FormField label="Servidor SMTP" name="smtp_host" defaultValue={data.smtp_host} /><FormField label="Porta" name="smtp_port" type="number" defaultValue={data.smtp_port || 465} /><FormField label="Segurança"><select className="form-control" name="smtp_secure" defaultValue={data.smtp_secure || "ssl"}><option value="ssl">SSL</option><option value="tls">TLS / STARTTLS</option><option value="none">Sem criptografia</option></select></FormField><FormField label="Usuário SMTP" name="smtp_user" defaultValue={data.smtp_user} /><FormField label="Senha SMTP" name="smtp_pass" type="password" defaultValue={data.smtp_pass} /><FormField label="E-mail remetente" name="smtp_from" type="email" defaultValue={data.smtp_from} /><FormField label="Nome remetente" name="smtp_from_name" defaultValue={data.smtp_from_name || "PlayMenu"} /></div><button className="btn btn-primary">Salvar SMTP</button></form></div></div></>;
}

export function VideoRequestsAdminPage() {
  const [params, setParams] = useSearchParams(); const status = params.get("status") || "all"; const { data } = useList("/superadmin/video-requests", { status });
  return <><AdminHeader title="Solicitações de Vídeo" /><div className="action-row" style={{ marginBottom: 20 }}>{["all", "pending", "done"].map((s) => <button key={s} className={`btn btn-sm ${status === s ? "btn-primary" : "btn-outline"}`} onClick={() => setParams({ status: s })}>{s === "all" ? "Todas" : s === "pending" ? "Pendentes" : "Respondidas"}</button>)}</div><div className="card"><div className="card-body">{!data.length ? <Empty text="Nenhuma solicitação." /> : <Table headers={["Imagem", "Título", "Restaurante", "Status", "Data", "Ação"]} rows={data} render={(r) => <tr key={r.id}><td>{r.image_file ? <img src={mediaUrl(r.image_file)} width="48" height="48" style={{ objectFit: "cover", borderRadius: 8 }} alt="" /> : "—"}</td><td><strong>{r.title}</strong></td><td>{r.restaurant_name}</td><td><Badge tone={r.status === "done" ? "green" : "orange"}>{r.status}</Badge></td><td>{r.created_at}</td><td><Link className="btn btn-sm btn-outline" to={`/superadmin/solicitacao?id=${r.id}`}>Ver</Link></td></tr>} />}</div></div></>;
}

export function VideoRequestDetailPage() {
  const [params] = useSearchParams(); const id = Number(params.get("id") || 0); const { data, load } = useLoad(`/superadmin/video-requests/${id}`); const [notice, setNotice] = useState({});
  const download = async (url, filename) => { try { const response = await api.get(url, { responseType: "blob" }); const href = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = href; const extensions = { "image/jpeg": ".jpg", "image/png": ".png", "image/webp": ".webp", "image/gif": ".gif" }; link.download = filename.includes(".") ? filename : `${filename}${extensions[response.data.type] || ".jpg"}`; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(href), 1000); } catch (err) { setNotice({ error: "Não foi possível baixar a imagem." }); } };
  if (!data) return <Empty text="Carregando solicitação..." />;
  const submit = async (e, itemId = 0) => { e.preventDefault(); const fd = new FormData(e.currentTarget); fd.set("target_item", itemId); try { await api.post(`/superadmin/video-requests/${id}/respond`, fd); setNotice({ message: "Vídeo enviado ao restaurante." }); load(); } catch (err) { setNotice({ error: err.response?.data?.detail }); } };
  const images = data.items.filter((item) => item.image_file);
  return <><AdminHeader title={`Solicitação #${id}`} /><Notice notice={notice} /><div className="request-page-actions"><Link className="btn btn-sm btn-outline" to="/superadmin/solicitacoes"><i className="fas fa-arrow-left" />Voltar</Link>{images.length > 0 && <button className="btn btn-sm btn-primary" type="button" onClick={() => download(`/superadmin/video-requests/${id}/images/download`, `solicitacao-${id}-imagens.zip`)}><i className="fas fa-download" />Baixar todas as imagens ({images.length})</button>}</div><div className="card request-detail-card"><div className="card-header"><h3>{data.request.title}</h3><Badge tone={data.request.status === "done" ? "green" : "orange"}>{data.request.status}</Badge></div><div className="card-body">{data.request.notes && <p className="request-notes">{data.request.notes}</p>}<div className="request-items">{data.items.map((item) => { const title = item.product?.title || `Produto #${item.product_id}`; return <article className="request-item" key={item.id}><div className="request-item__media">{item.image_file ? <><img src={mediaUrl(item.image_file)} alt={title} /><button className="btn btn-sm btn-outline" type="button" onClick={() => download(`/superadmin/video-requests/${id}/images/${item.id}/download`, title)}><i className="fas fa-download" />Baixar imagem</button></> : <div className="request-item__placeholder"><i className="fas fa-image" />Sem imagem</div>}</div><div className="request-item__content"><h4>{title}</h4>{item.video_file && <video src={mediaUrl(item.video_file)} controls />}<form onSubmit={(e) => submit(e, item.id)}><FormField label="Vídeo deste produto" name="video_file" type="file" required /><button className="btn btn-primary">{item.video_file ? "Atualizar vídeo" : "Enviar vídeo"}</button></form></div></article>; })}</div><form className="request-response-form" onSubmit={(e) => submit(e, 0)}><FormField label="Mensagem geral"><textarea className="form-control" name="response_notes" defaultValue={data.request.response_notes} /></FormField><button className="btn btn-outline">Salvar mensagem / marcar concluído</button></form></div></div></>;
}
