import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { api, mediaUrl, money } from "../services/api";
import { useLegacyStyles } from "../hooks/useLegacyStyles";

const allergenIcons = { gluten: "🌾", dairy: "🥛", eggs: "🥚", soy: "🫘", nuts: "🥜", shellfish: "🦐", fish: "🐟", celery: "🥬", mustard: "🟡", sesame: "⚫" };

export default function PublicMenu({ preview = false }) {
  useLegacyStyles("/public/assets/css/app.css", "public-menu-page");
  const [params, setParams] = useSearchParams(); const [data, setData] = useState(null); const [error, setError] = useState(""); const [product, setProduct] = useState(null); const [reviewsOpen, setReviewsOpen] = useState(false); const [rating, setRating] = useState(5); const [reviewNotice, setReviewNotice] = useState("");
  const query = { r: params.get("r") || "", q: params.get("q") || "", cat: Number(params.get("cat") || 0), preview };
  const queryKey = JSON.stringify(query);
  const load = () => api.get("/public/menu", { params: JSON.parse(queryKey) }).then((r) => setData(r.data)).catch((e) => setError(e.response?.data?.detail || "Restaurante não encontrado."));
  useEffect(() => { load(); }, [queryKey]); // eslint-disable-line react-hooks/exhaustive-deps
  const openProduct = async (id) => { const { data: item } = await api.get(`/public/product/${id}`); setProduct(item); };
  const trackLink = (link_type, link_label) => api.post("/public/analytics", { event_type: "link_click", restaurant_id: data.restaurant.id, link_type, link_label }).catch(() => {});
  const submitReview = async (e) => { e.preventDefault(); const form = Object.fromEntries(new FormData(e.currentTarget)); try { await api.post("/public/reviews", { ...form, rating, restaurant_id: data.restaurant.id }); setReviewNotice("Obrigado pela avaliação. Ela será exibida depois da aprovação do restaurante."); setReviewsOpen(false); } catch (err) { setReviewNotice(err.response?.data?.detail || "Não foi possível enviar."); } };
  const featured = useMemo(() => (data?.products || []).filter((p) => p.is_featured), [data]);
  const groups = useMemo(() => {
    if (!data) return [];
    return data.categories.map((category) => ({ category, products: data.products.filter((p) => !p.is_featured && p.category_id === category.id) })).filter((x) => x.products.length);
  }, [data]);
  if (error) return <div className="emptyState" role="alert">{error}</div>;
  if (!data) return <div className="emptyState">Carregando cardápio...</div>;
  const { restaurant, settings, reviews, reviews_summary: summary } = data; const logo = mediaUrl(settings.logo_image); const cover = mediaUrl(settings.cover_image); const extraLinks = Array.isArray(settings.social_links) ? settings.social_links : [];
  return <>
    {params.get("from") === "admin" && <Link to="/admin/" className="public-back-link">Voltar ao painel</Link>}
    <div className="hero"><div className="cover" style={{ backgroundImage: cover ? `url(${cover})` : "linear-gradient(180deg,#222,#000)" }} /><div className="heroContent"><div className="logoBox">{logo ? <img src={logo} alt="Logo" /> : <span>LOGO</span>}</div><div className="storeTitle">{settings.store_name}</div><p className="storeTag">{settings.tagline}</p><div className="socialIcons">{settings.instagram && <a className="socialIcon" href={`https://instagram.com/${String(settings.instagram).replace("@", "")}`} target="_blank" rel="noreferrer" onClick={() => trackLink("instagram", "Instagram")} aria-label="Instagram"><i className="fab fa-instagram" /></a>}{settings.whatsapp && <a className="socialIcon" href={`https://wa.me/55${String(settings.whatsapp).replace(/\D/g, "")}`} target="_blank" rel="noreferrer" onClick={() => trackLink("whatsapp", "WhatsApp")} aria-label="WhatsApp"><i className="fab fa-whatsapp" /></a>}{extraLinks.map((link, i) => <a key={i} className="socialIcon" href={link.url} target="_blank" rel="noreferrer" title={link.name} onClick={() => trackLink(link.type || "other", link.name)}><i className={link.icon || "fas fa-link"} /></a>)}</div><div className="steps">Assista <span className="dot">•</span> Escolha <span className="dot">•</span> Peça</div></div></div>
    <div className="container"><div className="searchWrap"><svg className="searchIcon" viewBox="0 0 24 24"><circle cx="10" cy="10" r="7" stroke="currentColor" fill="none" /><path d="m16 16 5 5" stroke="currentColor" /></svg><form onSubmit={(e) => { e.preventDefault(); setParams({ r: restaurant.slug, q: new FormData(e.currentTarget).get("q"), cat: query.cat || "" }); }}><input className="search" name="q" defaultValue={query.q} placeholder="Buscar pratos..." /></form></div><div className="chips"><button className={`chip ${!query.cat ? "active" : ""}`} onClick={() => setParams({ r: restaurant.slug, q: query.q })}>Todos</button>{data.categories.map((c) => <button key={c.id} className={`chip ${query.cat === c.id ? "active" : ""}`} onClick={() => setParams({ r: restaurant.slug, q: query.q, cat: c.id })}>{c.name.toUpperCase()}</button>)}</div>{reviewNotice && <div className="reviewNotice" role="status">{reviewNotice}</div>}<div className="reviewsEntry"><button className="reviewsEntryBtn" onClick={() => setReviewsOpen(true)}><span className="reviewsStars">{"★".repeat(Math.max(1, Math.round(summary.avg_rating || 5)))}</span><span><strong>Avaliações do Restaurante</strong><small>{summary.total ? `${summary.avg_rating.toFixed(1).replace(".", ",")} de 5 em ${summary.total} avaliações` : "Seja o primeiro a avaliar"}</small></span></button></div>
      {!data.products.length && <div className="emptyState">Nenhum prato encontrado.</div>}
      {featured.map((p) => <button className="featured" key={p.id} onClick={() => openProduct(p.id)}><div className="thumb" style={{ backgroundImage: p.image_url ? `url(${mediaUrl(p.image_url)})` : "linear-gradient(135deg,#2a2a2f,#111)" }} /><div className="featuredShade" /><div className="cornerLogo">{logo ? <img src={logo} alt="Logo" /> : "M"}</div><div className="featuredBadge"><span>{p.featured_icon || "🔥"}</span><span>{p.featured_label || "Mais pedido hoje"}</span></div>{p.video_url && <div className="playBtn"><i className="fas fa-play" /></div>}<div className="featuredBody"><div className="featuredTitle">{p.title}</div><p className="featuredDesc">{p.description}</p>{p.allergens && <div className="allergenPill">{String(p.allergens).split(",").map((a) => <span key={a}>{allergenIcons[a] || "⚠️"}</span>)}</div>}<div className="featuredFoot"><div className="price">{money(p.price_cents)}</div>{p.ar_model_url && <span className="arBtn"><i className="fas fa-cube" /></span>}</div></div></button>)}
      {groups.map(({ category, products }) => <section key={category.id}><div className="section">{category.name.toUpperCase()}</div><div className="menuGrid">{products.map((p) => <button className="pcard" key={p.id} onClick={() => openProduct(p.id)}><div className="pcThumb" style={{ backgroundImage: p.image_url ? `url(${mediaUrl(p.image_url)})` : "linear-gradient(135deg,#2a2a2f,#111)" }} /><div className="pcShade" /><div className="pcLogo">{logo ? <img src={logo} alt="Logo" /> : "M"}</div>{p.video_url && <div className="playBtn small"><i className="fas fa-play" /></div>}<div className="pcBody"><div className="pcTitle">{p.title}</div>{p.allergens && <div className="allergenPill">{String(p.allergens).split(",").map((a) => <span key={a}>{allergenIcons[a] || "⚠️"}</span>)}</div>}<div className="pcFoot"><div className="price sm">{money(p.price_cents)}</div>{p.ar_model_url && <span className="arBtn sm"><i className="fas fa-cube" /></span>}</div></div></button>)}</div></section>)}
    </div>
    {reviewsOpen && <div className="reviewsModal show" onClick={(e) => e.target === e.currentTarget && setReviewsOpen(false)}><div className="reviewsDialog"><div className="reviewsHead"><div><span>Avaliações do Restaurante</span><strong>{settings.store_name}</strong></div><button className="reviewsClose" onClick={() => setReviewsOpen(false)}>×</button></div><div className="reviewsBody"><div className="approvedReviews">{reviews.length ? reviews.map((review) => <div className="reviewCard" key={review.id}><div className="reviewCardTop"><strong>{review.customer_name || "Cliente"}</strong><span>{"★".repeat(review.rating)}</span></div><p>{review.comment}</p></div>) : <div className="reviewEmpty">Ainda não existem avaliações aprovadas.</div>}</div><form className="reviewForm" onSubmit={submitReview}><h3>Deixe sua avaliação</h3><div className="ratingPicker">{[1, 2, 3, 4, 5].map((n) => <button type="button" className={n <= rating ? "active" : ""} onClick={() => setRating(n)} key={n}>★</button>)}</div><input className="reviewInput" name="customer_name" maxLength="120" placeholder="Seu nome (opcional)" /><textarea className="reviewTextarea" name="comment" maxLength="1000" rows="4" placeholder="Conte como foi sua experiência" /><button className="reviewSubmit">Enviar para aprovação</button></form></div></div></div>}
    {product && <div className="modal show" onClick={(e) => e.target === e.currentTarget && setProduct(null)}><button className="modalIconBtn modalCloseBtn" onClick={() => setProduct(null)}>✕</button><div className="modalVideoWrap">{product.video_url ? <video src={mediaUrl(product.video_url)} autoPlay muted controls playsInline /> : product.image_url ? <img className="modalImage" style={{ display: "block" }} src={mediaUrl(product.image_url)} alt={product.title} /> : null}</div><div className="sheet"><div className="sheetTop"><div className="sheetTitle">{product.title}</div></div><div className="sheetDescWrap"><p className="sheetDesc expanded">{product.description}</p></div><div className="sheetBottom"><div className="sheetPrice">{product.price}</div>{product.ar_model_url && <a className="arPlaceBtn" href={mediaUrl(product.ar_model_url)} target="_blank" rel="noreferrer"><i className="fas fa-cube" />Visualizar em 3D</a>}</div></div></div>}
  </>;
}