import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../services/api";
import { useLegacyStyles } from "../hooks/useLegacyStyles";

export default function WizardPage() {
  useLegacyStyles("/public/assets/css/playmenu-ui.css", "ui-kit-page restaurant-admin-page ui-wizard-page");
  const navigate = useNavigate(); const [step, setStep] = useState(0); const [settings, setSettings] = useState({ store_name: "", instagram: "", whatsapp: "", address: "", latitude: "", longitude: "" }); const [error, setError] = useState("");
  useEffect(() => { api.get("/restaurant/settings").then(({ data }) => setSettings((s) => ({ ...s, ...data }))); }, []);
  const submit = async (e) => { e.preventDefault(); const fd = new FormData(e.currentTarget); try { await api.post("/restaurant/wizard", fd); navigate("/admin/"); } catch (err) { setError(err.response?.data?.detail || "Não foi possível salvar."); } };
  const fields = [
    <div className="ui-field"><label>Nome do estabelecimento</label><input name="store_name" value={settings.store_name} onChange={(e) => setSettings({ ...settings, store_name: e.target.value })} required /></div>,
    <label className="ui-upload-zone"><input type="file" name="logo_image" accept=".png,.jpg,.jpeg,.webp" /><strong>Selecione ou arraste sua logo</strong><span>PNG, JPG ou WebP de até 2 MB.</span></label>,
    <label className="ui-upload-zone"><input type="file" name="cover_image" accept=".png,.jpg,.jpeg,.webp" /><strong>Selecione ou arraste a imagem de capa</strong><span>PNG, JPG ou WebP de até 5 MB.</span></label>,
    <div className="ui-stack"><div className="ui-field"><label>Endereço</label><input name="address" value={settings.address || ""} onChange={(e) => setSettings({ ...settings, address: e.target.value })} /></div><div className="ui-form-grid ui-form-grid--2"><div className="ui-field"><label>Latitude</label><input name="latitude" value={settings.latitude || ""} onChange={(e) => setSettings({ ...settings, latitude: e.target.value })} /></div><div className="ui-field"><label>Longitude</label><input name="longitude" value={settings.longitude || ""} onChange={(e) => setSettings({ ...settings, longitude: e.target.value })} /></div></div></div>,
    <div className="ui-form-grid ui-form-grid--2"><div className="ui-field"><label>Instagram</label><input name="instagram" value={settings.instagram || ""} onChange={(e) => setSettings({ ...settings, instagram: e.target.value })} /></div><div className="ui-field"><label>WhatsApp</label><input name="whatsapp" value={settings.whatsapp || ""} onChange={(e) => setSettings({ ...settings, whatsapp: e.target.value })} /></div></div>,
    <div className="ui-preview-card-admin"><div className="ui-preview-card-admin__info"><div className="ui-preview-card-admin__logo"><span>Logo</span></div><div className="ui-preview-card-admin__name">{settings.store_name || "Sua Loja"}</div><div className="ui-preview-card-admin__social">{settings.instagram && <i className="fab fa-instagram" />}{settings.whatsapp && <i className="fab fa-whatsapp" />}</div></div></div>,
  ];
  const titles = ["Como sua loja se chama?", "Adicione sua logo", "Escolha uma imagem de capa", "Onde fica o estabelecimento?", "Como seus clientes entram em contato?", "Tudo pronto para começar"];
  return <main className="ui-wizard-shell"><header className="ui-wizard-topbar"><div className="ui-wizard-brand"><img src="/public/assets/images/logopm.png" alt="" /><strong>PlayMenu</strong></div><span className="ui-badge ui-badge--accent">Configuração inicial</span></header><section className="ui-wizard-card"><header className="ui-wizard-header"><span className="ui-eyebrow">Primeiros passos</span><h1>Prepare seu restaurante para o PlayMenu</h1><p>Complete as seis etapas para organizar identidade, localização, contato e apresentação final.</p></header><div className="ui-wizard-progress" style={{ "--wizard-progress": `${((step + 1) / 6) * 100}%` }}><div className="ui-progress"><span /></div><ol className="ui-wizard-steps">{["Nome", "Logo", "Capa", "Endereço", "Contato", "Revisão"].map((label, i) => <li className={`ui-wizard-step ${i === step ? "active" : i < step ? "done" : ""}`} key={label}><span>{i + 1}</span><small>{label}</small></li>)}</ol></div><form className="ui-wizard-form" onSubmit={submit} encType="multipart/form-data">{error && <div className="ui-alert ui-alert--danger" role="alert">{error}</div>}<section className="ui-wizard-panel active"><div className="ui-wizard-step-head"><span className="ui-wizard-step-icon"><i className="fas fa-store" /></span><div><span className="ui-eyebrow">Etapa {step + 1} de 6</span><h2>{titles[step]}</h2></div></div>{fields[step]}<div className="ui-wizard-actions">{step > 0 && <button type="button" className="ui-btn ui-btn--outline" onClick={() => setStep(step - 1)}>Voltar</button>}{step < 5 ? <button type="button" className="ui-btn ui-btn--primary" onClick={() => { if (step || settings.store_name.trim()) setStep(step + 1); }}>Próximo</button> : <button className="ui-btn ui-btn--primary ui-btn--lg">Salvar e acessar painel</button>}</div></section></form></section></main>;
}